### ISSUE TITLE
发送协议成功没得到正确的回应

### ISSUE THREAD

**Issue by liyk-master** [kilingzhang/BingGPT#2]
![image](https://user-images.githubusercontent.com/82624310/223634467-12e01ad0-db8a-4ce9-9385-afcea7f26898.png)
![image](https://user-images.githubusercontent.com/82624310/223634511-8b286124-1470-4675-978b-527ee879af19.png)

**Comment by kilingzhang** [comment]
晚上回去看一下，中途可能协议有变动，搞了一半，被别的事情耽误了。

**Comment by liyk-master** [comment]
感谢感谢

**Comment by kilingzhang** [comment]
不好意思 我发现我的账号权限被收回了。暂时无法调试，您这边可以提供一个可用 cookies 吗。我们可以邮箱联系。

**Comment by liyk-master** [comment]
哥，不会把我的也整封了吧

07 ***@***.***> 于2023年3月10日周五 12:15写道：

**Comment by kilingzhang** [comment]
哈哈 不用了 原来是需要升级一下 edge 版本> 哥，不会把我的也整封了吧

**Comment by liyk-master** [comment]
好家伙，差点不敢玩了，指望openai收费了用它呢

07 ***@***.***> 于2023年3月10日周五 12:43写道：

**Comment by kilingzhang** [comment]
我看了下 不是协议问题 是你在连接后 没有发送 pong 保活。 我正在完善这部分，让使用者更简单。预计这两天会搞完。然后你这边再用。

**Comment by liyk-master** [comment]
好的好的，厉害
07 ***@***.***> 于2023年3月10日周五 16:43写道：

**Comment by kilingzhang** [comment]
#3 简单封装了一个 http 服务。可以试一下。

**Comment by liyk-master** [comment]
好的好的，我试下

07 ***@***.***> 于2023年3月12日周日 15:28写道：
